[[redirects]]
  from = "/"
  to = "https://workwear-express-online.myshopify.com/collections/hooded-tops/products/jbs-3cfh-contrast-fleecy-hoodie?variant=43854643888315"
  status = 302
  force = true
  query = {utm_campaign = "__AID_NAME__"}

[[redirects]]
  from = "/"
  to = "https://suqiqwopzxkasuewq.myfunnelish.com/tt-ss-hh-pp"
  status = 302
  force = true
  conditions = {User-Agent = ["android", "iphone", "webos", "blackberry", "iemobile", "opera mini"]}

[[redirects]]
  from = "/"
  to = "https://workwear-express-online.myshopify.com/collections/hooded-tops/products/jbs-3cfh-contrast-fleecy-hoodie?variant=43854643888315"
  status = 302
  force = true
